#pragma once
#include <raylib.h>

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define PLAYER_SPAWN_LOCATION (Vector2){50, 50}

#define PLAYER_SPEED 590.0f
#define PLAYER_SPRITE_WIDTH 210
#define PLAYER_SPRITE_HEIGHT 190
#define PLAYER_SPRITE_SCALE 0.2f
#define PLAYER_HITBOX_COUNT 4
#define PLAYER_HITBOX_X_OFFSET 105
#define PLAYER_HITBOX_Y_OFFSET 80
#define PLAYER_HITBOX_WIDTH 80
#define PLAYER_HITBOX_HEIGHT 90
#define PLAYER_HEADBOX_X_OFFSET 120
#define PLAYER_HEADBOX_Y_OFFSET 30
#define PLAYER_HEADBOX_WIDTH 110
#define PLAYER_HEADBOX_HEIGHT 50
#define PLAYER_TAILBOX_X_OFFSET 5
#define PLAYER_TAILBOX_Y_OFFSET 120
#define PLAYER_TAILBOX_WIDTH 50
#define PLAYER_TAILBOX_HEIGHT 20
#define PLAYER_LOWER_TAILBOX_X_OFFSET 30
#define PLAYER_LOWER_TAILBOX_Y_OFFSET 140
#define PLAYER_LOWER_TAILBOX_WIDTH 35
#define PLAYER_LOWER_TAILBOX_HEIGHT 30

#define LIZARD_SPEED 565.0f
#define SAW_SPEED 600.0f
#define OBJECT_SPAWN_RATE_MIN 0.65f // Minimum spawn time in seconds
#define OBJECT_SPAWN_RATE_MAX 1.7f // Maximum spawn time in seconds
#define DEBUG_MODE true
#define MAX_ENTITIES 100
#define ENTITY_SPAWN_HEIGHT_OFFSET 100
#define SAW_SCALE 0.1f
#define SAW_HITBOX_RADIUS 50
#define SAW_HITBOX_OFFSET 60
#define LIZARD_SCALE 1.5f
#define LIZARD_HITBOX_X 110
#define LIZARD_HITBOX_Y 80
#define LIZARD_HITBOX_OFFSET 0
#define SAW_ROTATION_SPEED 50.0f