#pragma once
#include <raylib.h>

#define PLAYER_SPAWN_LOCATION (Vector2){50, 50}

#define PLAYER_SPEED 420.0f
#define PLAYER_SPRITE_WIDTH 210
#define PLAYER_SPRITE_HEIGHT 190
#define PLAYER_SPRITE_SCALE 0.2f
#define PLAYER_HITBOX_X_OFFSET 45
#define PLAYER_HITBOX_Y_OFFSET 80
#define PLAYER_HITBOX_WIDTH 75
#define PLAYER_HITBOX_HEIGHT 70
#define PLAYER_HEADBOX_X_OFFSET 50
#define PLAYER_HEADBOX_Y_OFFSET 20
#define PLAYER_HEADBOX_WIDTH 100
#define PLAYER_HEADBOX_HEIGHT 50

#define LIZARD_SPEED 570.0f
#define SAW_SPEED 600.0f
#define OBJECT_SPAWN_RATE_MIN 0.65f // Minimum spawn time in seconds
#define OBJECT_SPAWN_RATE_MAX 1.7f // Maximum spawn time in seconds
#define DEBUG_MODE true
#define MAX_ENTITIES 100
#define ENTITY_SPAWN_HEIGHT_OFFSET 100
#define SAW_SCALE 0.1f
#define SAW_HITBOX_RADIUS 50
#define SAW_HITBOX_OFFSET 60
#define LIZARD_SCALE 1.5f
#define LIZARD_HITBOX_X 110
#define LIZARD_HITBOX_Y 80
#define LIZARD_HITBOX_OFFSET 0
#define SAW_ROTATION_SPEED 50.0f