#pragma once
#include <raylib.h>

#define DEBUG_MODE false
#define GAME_TITLE "LIZARD! LIZARD! LIZARD!!!"
//#define BACKGROUND_BUFFER_COLOR (Color) {248, 58, 95, 255}
#define BACKGROUND_BUFFER_COLOR RED

#define VIRTUAL_SCREEN_WIDTH 1920
#define VIRTUAL_SCREEN_HEIGHT 1080
#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define MAIN_MENU_BUTTON_WIDTH 300
#define MAIN_MENU_BUTTON_HEIGHT 80
#define MAIN_MENU_BUTTON_FONT_SIZE 42
#define MAIN_MENU_BUTTON_PADDING 20

#define SCORE_FONT_SIZE 60

#define PLAYER_SPAWN_LOCATION (Vector2){50, 50}
#define PLAYER_SPEED 620.0f
#define PLAYER_SPRITE_WIDTH 210
#define PLAYER_SPRITE_HEIGHT 190
#define PLAYER_SPRITE_SCALE 0.15f
#define PLAYER_HITBOX_COUNT 4
#define PLAYER_HITBOX_X_OFFSET 75
#define PLAYER_HITBOX_Y_OFFSET 55
#define PLAYER_HITBOX_WIDTH 70
#define PLAYER_HITBOX_HEIGHT 70
#define PLAYER_HEADBOX_X_OFFSET 90
#define PLAYER_HEADBOX_Y_OFFSET 25
#define PLAYER_HEADBOX_WIDTH 80
#define PLAYER_HEADBOX_HEIGHT 40
#define PLAYER_TAILBOX_X_OFFSET 0
#define PLAYER_TAILBOX_Y_OFFSET 90
#define PLAYER_TAILBOX_WIDTH 40
#define PLAYER_TAILBOX_HEIGHT 20
#define PLAYER_LOWER_TAILBOX_X_OFFSET 20
#define PLAYER_LOWER_TAILBOX_Y_OFFSET 110
#define PLAYER_LOWER_TAILBOX_WIDTH 30
#define PLAYER_LOWER_TAILBOX_HEIGHT 15

#define LIZARD_SPEED 565.0f
#define SAW_SPEED 600.0f
#define OBJECT_SPAWN_RATE_MIN 0.65f // Minimum spawn time in seconds
#define OBJECT_SPAWN_RATE_MAX 1.7f // Maximum spawn time in seconds
#define MAX_ENTITIES 100
#define ENTITY_SPAWN_HEIGHT_OFFSET 100
#define SAW_SCALE 0.08f
#define SAW_HITBOX_RADIUS 42
#define SAW_HITBOX_OFFSET 48
#define LIZARD_SCALE 1.1f
#define LIZARD_HITBOX_X 80
#define LIZARD_HITBOX_Y 60
#define LIZARD_HITBOX_OFFSET 0
#define SAW_ROTATION_SPEED 600.0f