#pragma once

const char* shader_flash_fs = 
"#version 100\n"
"precision mediump float;\n"
"\n"
"// Input vertex attributes (from vertex shader)\n"
"varying vec2 fragTexCoord;\n"
"varying vec4 fragColor;\n"
"\n"
"// Input uniform values\n"
"uniform sampler2D texture0;\n"
"uniform vec4 colDiffuse;\n"
"\n"
"// Flash effect uniforms\n"
"uniform float flashIntensity;  // 0.0 = no flash, 1.0 = full white flash\n"
"uniform vec3 flashColor;       // Color of the flash (usually white)\n"
"\n"
"void main()\n"
"{\n"
"    // Sample the texture\n"
"    vec4 texelColor = texture2D(texture0, fragTexCoord);\n"
"    \n"
"    // Apply base tinting\n"
"    vec4 baseColor = texelColor * colDiffuse * fragColor;\n"
"    \n"
"    // Apply flash effect by mixing with flash color\n"
"    // When flashIntensity is 0, use original color\n"
"    // When flashIntensity is 1, use flash color\n"
"    vec3 flashedColor = mix(baseColor.rgb, flashColor, flashIntensity);\n"
"    \n"
"    // Preserve original alpha\n"
"    gl_FragColor = vec4(flashedColor, baseColor.a);\n"
"}\n";